name: Build Kiwix Android (Debug)
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17' # Kiwix README says JDK 17
      - uses: gradle/actions/setup-gradle@v3
      - name: Build debug APKs
        run: ./gradlew --no-daemon clean assembleDebug
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: "**/build/outputs/apk/**/*.apk"
