name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  automated-tests:
    name: Automated tests
    strategy:
      matrix:
        api-level: [ 25, 30, 33, 34 ]
      fail-fast: true
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: create instrumentation coverage
        uses: reactivecircus/android-emulator-runner@v2
        env:
          GRADLE_OPTS: "-Dorg.gradle.internal.http.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.network.retry.max.attempts=6 -Dorg.gradle.internal.network.retry.initial.backOff=2000"
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86_64
          profile: pixel_2
          ram-size: 4096M
          cores: 4
          sdcard-path-or-size: 2048M
          disable-animations: true
          heap-size: 512M
          emulator-boot-timeout: 1200
          script: bash contrib/instrumentation.sh

      - name: Test custom app
        uses: reactivecircus/android-emulator-runner@v2
        env:
          GRADLE_OPTS: "-Dorg.gradle.internal.http.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.network.retry.max.attempts=6 -Dorg.gradle.internal.network.retry.initial.backOff=2000"
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86_64
          profile: pixel_2
          ram-size: 4096M
          cores: 4
          sdcard-path-or-size: 2048M
          disable-animations: true
          emulator-boot-timeout: 1200
          heap-size: 512M
          script: bash contrib/instrumentation-customapps.sh


      - name: Upload screenshot result
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ matrix.api-level }}
          path: screencap.png

      - name: create unit coverage
        if: ${{ matrix.api-level==25 }}
        run: ./gradlew testDebugUnitTest testCustomexampleDebugUnitTest

      - name: Upload coverage to Codecov
        if: ${{ matrix.api-level==25 }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Coverage to GH-Actions
        uses: actions/upload-artifact@v3
        if: ${{ matrix.api-level==25 }}
        with:
          name: Tests Coverage Report
          path: |
            **/reports/
