name: Publish App to Play Store

# This workflow is triggered on a schedule or when specific tags are pushed.
# It runs every Monday at 12:00 UTC and also when the 'internal_testing' or 'internal_testing_v*' tag is pushed.
# In 'internal_testing_v*', '*' represents a dynamic date (e.g., 2024-12-18).
on:
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00
  push:
    tags:
      - 'internal_testing' # internal_testing Tag
      - 'internal_testing_v*' # Dynamic date tag for internal testing

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Retrieve secrets to files
        env:
          KEYSTORE: ${{ secrets.keystore }}
          PLAYSTORE_JSON: ${{ secrets.PLAYSTORE_JSON }}
        run: |
          echo "$KEYSTORE" | base64 -d > kiwix-android.keystore
          echo "$PLAYSTORE_JSON" > playstore.json

      - name: Retrieve date from TAG
        id: extract_date
        run: |
          # Check if the tag matches the pattern 'internal_testing_vYYYY-MM-DD'.
          # If the date is found in the tag, it will be extracted and set as the RELEASE_DATE.
          # If no date is found or the tag does not match, an empty string will be set for RELEASE_DATE.
          # Android will use the current date for the APK generation.
          if [[ "${GITHUB_REF}" =~ internal_testing_v([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
             RELEASE_DATE="${BASH_REMATCH[1]}"
          else
             RELEASE_DATE=""
          fi
          echo "KIWIX_ANDROID_RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Publish bundle in internal testing on Google Play
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KIWIX_ANDROID_RELEASE_DATE: ${{ env.KIWIX_ANDROID_RELEASE_DATE }}
        run: |
          ./gradlew publishPlayStoreBundle --scan
