name: Publish App to Play Store

# Trigger the workflow on a schedule (every Monday at 12:00 UTC)
on:
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00
  push:
    tags:
      - 'internal_testing' # internal_testing Tag

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Retrieve secrets to files
        env:
          KEYSTORE: ${{ secrets.keystore }}
          PLAYSTORE_JSON: ${{ secrets.PLAYSTORE_JSON }}
        run: |
          echo "$KEYSTORE" | base64 -d > kiwix-android.keystore
          echo "$PLAYSTORE_JSON" > playstore.json

      - name: Publish bundle in internal testing on Google Play
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: |
          ./gradlew publishPlayStoreBundle --scan
